export const TODODACTIONS = {
    ADD_TODO : "ADD_TODO",
    ADD_TODO_COMMIT : "ADD_TODO_COMMIT",
    ADD_TODO_ROLLBACK : "ADD_TODO_ROLLBACK",
    REMOVE_TODO : "REMOVE_TODO",
    REMOVE_TODO_COMMIT : "REMOVE_TODO_COMMIT",
    REMOVE_TODO_ROLLBACK : "REMOVE_TODO_ROLLBACK",
}